apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nimbus-signals-price-service
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/asads-cloud/nimbus-signals.git
    targetRevision: main
    path: apps/price-service/helm/price-service
    helm:
      releaseName: price-service
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: platform

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
