apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nimbus-signals-root
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/asads-cloud/nimbus-signals.git
    targetRevision: main
    path: platform/argocd

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
